// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbJuwAWp9HQQGHSQJAYCGeeJ4-ezfhwTE',
    appId: '1:651992733520:web:66ac73c3918adc87117e55',
    messagingSenderId: '651992733520',
    projectId: 'lsrd-pro',
    authDomain: 'lsrd-pro.firebaseapp.com',
    storageBucket: 'lsrd-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4DC9qiR1bFkFjVj7m5weHq7UBrOfrOQ',
    appId: '1:651992733520:android:a485ace9c4458f7a117e55',
    messagingSenderId: '651992733520',
    projectId: 'lsrd-pro',
    storageBucket: 'lsrd-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7lEqO-Im9_pEa9jS6H_S7V2m44R1WH9c',
    appId: '1:651992733520:ios:8f3c27bc1823b8f8117e55',
    messagingSenderId: '651992733520',
    projectId: 'lsrd-pro',
    storageBucket: 'lsrd-pro.firebasestorage.app',
    iosBundleId: 'com.example.lsrdPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7lEqO-Im9_pEa9jS6H_S7V2m44R1WH9c',
    appId: '1:651992733520:ios:8f3c27bc1823b8f8117e55',
    messagingSenderId: '651992733520',
    projectId: 'lsrd-pro',
    storageBucket: 'lsrd-pro.firebasestorage.app',
    iosBundleId: 'com.example.lsrdPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbJuwAWp9HQQGHSQJAYCGeeJ4-ezfhwTE',
    appId: '1:651992733520:web:a6fa2f992aaca8d5117e55',
    messagingSenderId: '651992733520',
    projectId: 'lsrd-pro',
    authDomain: 'lsrd-pro.firebaseapp.com',
    storageBucket: 'lsrd-pro.firebasestorage.app',
  );
}
