 // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD_g3JE10E2Rs8F6DsgUYAvf8xPd8LPogY',
//     appId: '1:547891733975:web:b2ba610faf22318fed5792',
//     messagingSenderId: '547891733975',
//     projectId: 'auth-7fa36',
//     authDomain: 'auth-7fa36.firebaseapp.com',
//     storageBucket: 'auth-7fa36.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCIRsuHkoG1g8YVYLSsR4vggxQ6H1nFqyc',
//     appId: '1:547891733975:android:e7a7b4097a1149cded5792',
//     messagingSenderId: '547891733975',
//     projectId: 'auth-7fa36',
//     storageBucket: 'auth-7fa36.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAt-29FGhg5MF0GJh48fk57rPrh4oXKsXs',
//     appId: '1:547891733975:ios:69fff4581380f576ed5792',
//     messagingSenderId: '547891733975',
//     projectId: 'auth-7fa36',
//     storageBucket: 'auth-7fa36.firebasestorage.app',
//     iosBundleId: 'com.example.lsrdPro',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAt-29FGhg5MF0GJh48fk57rPrh4oXKsXs',
//     appId: '1:547891733975:ios:69fff4581380f576ed5792',
//     messagingSenderId: '547891733975',
//     projectId: 'auth-7fa36',
//     storageBucket: 'auth-7fa36.firebasestorage.app',
//     iosBundleId: 'com.example.lsrdPro',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD_g3JE10E2Rs8F6DsgUYAvf8xPd8LPogY',
//     appId: '1:547891733975:web:a864a04479f183cbed5792',
//     messagingSenderId: '547891733975',
//     projectId: 'auth-7fa36',
//     authDomain: 'auth-7fa36.firebaseapp.com',
//     storageBucket: 'auth-7fa36.firebasestorage.app',
//   );
// }
